## Install the environement

In [ ]:
# $> git clone https://github.com/maximecb/gym-minigrid.git
# $> pip3 install -e gym-minigrid
# $> pip instal gym

## Import libs and usefull methods

In [2]:
import gym
import gym_minigrid

import time
import numpy as np

from q_learning import state_to_key, update_Q, create_state_if_not_exist

## Demonstration of the environement

In [3]:
Q = {}
env = gym.make("MiniGrid-Empty-6x6-v0")

for epoch in range(100):
    s = env.reset()
    s = state_to_key(s)
    done = False

    while not done:
        create_state_if_not_exist(Q, s)
        sp, r, done, info = env.step(np.random.randint(0, 4))
        sp = state_to_key(sp)
        s = sp
        env.render()

In [7]:
print(len(Q))
for state in Q:
    print(Q[state])

60
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


# Methods you can use

In [11]:
Q = {}
env = gym.make("MiniGrid-Empty-6x6-v0")
s = env.reset()
print(type(s))
s = state_to_key(s)
print(type(s))
# Create the state in the Q table if this state doesn't exist yet
create_state_if_not_exist(Q, s)
print("Actions for state s", Q[s])

# This method can be used to update the Q Table
update_Q(Q=Q, s=s, sp=s, a=0, r=0, done=False)

<class 'dict'>
<class 'str'>
Actions for state s [0. 0. 0. 0.]


## Train the agent

In [14]:
Q = {}
env = gym.make("MiniGrid-Empty-6x6-v0")

epochs_nb = 2
for epoch in range(epochs_nb):
    s = env.reset()
    s = state_to_key(s)
    done = False

    print("\r epoch=", epoch)
    
    while not done:
        create_state_if_not_exist(Q, s)
        # TODO
        # Take an action here with epsilon greedy instead of randint
        sp, r, done, info = env.step(np.random.randint(0, 4))
        sp = state_to_key(sp)
        # TODO
        # Call the update method
        s = sp

 epoch= 0
 epoch= 1


## Check the result

In [15]:
s = env.reset()
s = state_to_key(s)
done = False

while not done:
    create_state_if_not_exist(Q, s)
    sp, r, done, info = env.step(np.random.randint(0, 4))
    sp = state_to_key(sp)
    s = sp
    env.render()